version: '3.5'

services:
  django-backend:
    build:
      context: .
    container_name: quiz-backend
    ports:
      - "8000:8000"
    volumes:
        - '.:/usr/src:rw'
    command: bash run_command.sh
    env_file: .env
  db:
    image: postgres:16.3
    container_name: quiz-database
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
  maildev:
    image: maildev/maildev
    container_name: maildev
    ports:
      - "1025:1025"
      - "1080:1080"
    restart: always